version: 2.1
orbs:
  node: circleci/node@5

jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: App configuration
          command: |
            cp .env.example .env
      - run:
          name: Run tests
          command: npm run test:circle
      - run:
          name: Build the App
          command: |
            npm install
            npm run build
      - store_artifacts:
          path: coverage

  build-and-deploy:
    # Build node project
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: App configuration
          command: |
            cp .env.example .env
            # Append environment variables
            printenv | grep -v "^\s*$" >> .env  
            # Remove duplicate lines
            sort -u -o .env .env  
            # Remove lines with empty values
            sed -i '/=.*$/!d' .env
            sed -i '/=.*$/{/^.*=$/d}' .env
            cat .env
      - run:
          name: Run tests
          command: npm run test:circle
      - run:
          name: Build the App
          command: |
            npm install
            npm run build
      - run:
          name: Deploy on Firebase
          command: |
            echo $SA_KEY > credentials.json
            GOOGLE_APPLICATION_CREDENTIALS=credentials.json npm exec -- firebase deploy

workflows:
  test-branch:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - main
  deploy-production:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only: main
